### ISSUE TITLE
"TraceKit is not defined" when importing via NPM

### ISSUE THREAD

**Issue by poshaughnessy** [atatus/atatus-js#4]
Hi,

When running our mocha tests, I get _"ReferenceError: TraceKit is not defined"_:

```
ReferenceError: TraceKit is not defined
    at /Users/peter/dev/src/pebblecode/products/bybox-erskine-mercurial/node_modules/atatus-js/atatus.min.js:3:12890
    at Object.<anonymous> (/Users/peter/dev/src/pebblecode/products/bybox-erskine-mercurial/node_modules/atatus-js/atatus.min.js:3:20689)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/peter/dev/src/pebblecode/products/bybox-erskine-mercurial/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:356:32)
...
```

If I remove the "atatus-js" import, then the error goes away.

I am pulling in atatus-js via NPM. I've tried v2.3.7 and v2.3.11. 

In case it's relevant, I'm importing it in our "AtatusLogger.js" with `import 'atatus-js';` (this is transformed with Babel). The command I'm running is `mocha "test/**/*.@(js|jsx)"` and my .babelrc is just:

```
{
  "presets": ["react", "es2015"]
}

```

Please might you have any suggestions?

**Comment by fizerkhan** [comment]
I will look into it and let you know.

**Comment by fizerkhan** [comment]
It is fixed in recent release.
